apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.agentppz.image }}:{{ .Values.global.imageTag }}"
          env:
            - name: JAVA_EXT
              value: -Djava.security.egd=file:/dev/./urandom
            - name: JAVA_MEM
              value: -Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DATABASE
              value: {{ .Release.Name }}-postgre-agent-ppz.{{ .Release.Namespace }}
          ports:
            - containerPort: 8088
          imagePullPolicy: "{{ .Values.global.agentppz.imagePullPolicy }}"
          imagePullSecrets:
          - name: regsecret
          readinessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 600
            periodSeconds: 60
      imagePullSecrets: 
        - name: regsecret