apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: ms.127.0.0.1.nip.io
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" . }}
            servicePort: 80