global:
  imageTag: latest
  proxy:
    https:
      host: s-msk-proxy-01.global.bcs
      port: 8080
    http:
      host: s-msk-proxy-01.global.bcs
      port: 8080
    none:
      - kubernetes.default.svc.cluster.local

  msfront:
    image: ms-front
    imagePullPolicy: Never
